---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator-pod
          image: ayushitachi/orchestrator-droplet:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: env
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: ClusterIP
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-ingress
  annotations:
    kubernetes.io/ingress.class: nginx # or your specific ingress class
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # forces HTTPS
spec:
  tls:
    - hosts:
        - droplet.kubertestingayush.xyz
      secretName: my-tls-secret
  rules:
    - host: droplet.kubertestingayush.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestrator-service
                port:
                  number: 80
