---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator-pod
          image: ayushitachi/orchestrator-droplet:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: env
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: LoadBalancer
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
